### ISSUE TITLE
Wrong folder name in readme

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-tls#1]
In README.md chapter Building and running the examples:

"4. Build the application by selecting the board and build toolchain using the command mbed compile -m K64F -t GCC_ARM. mbed-cli builds a binary file under the project’s .build directory."

and

"6. Drag the binary .build/K64F/GCC_ARM/<EXAMPLE>.bin to the board to flash the application."

'.build' folder was not created, looks like it have been renamed to 'BUILD'
(mbed-os-example-tls/benchmark/BUILD/K64F/GCC_ARM)

**Comment by andresag01** [comment]
PR https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/14 fixes this issue.
