### ISSUE TITLE
tls-client IAR Does not connect to server

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-tls#12]
tls client example IAR application does not connect to server.

>Using Ethernet LWIP
>Client IP Address is 192.168.100.17
>Connecting with developer.mbed.org
>Starting the TLS handshake...
>mbedtls_ssl_handshake() failed: -0x262e (-9774): X509 - Signature algorithm (oid) is unsupported : OID - >OID is not found
>MBED: Socket Error: -1

HW:
K64F and Nucleo-F429ZI

Windows setup:
Windows 7
mbed-cli v.0.9.7
IAR for ARM vesion 7.70.2.11710

**Comment by andresag01** [comment]
PR https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/10 fixes this issue and has already been merged.
