### ISSUE TITLE
Benchmark example halts

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-tls#2]
Build and flashed benchmark example to K64F with GCC_ARM. Execution halts to ECDSA-secp384r1 test.

  SHA-256                  :       2060 Kb/s,         56 cycles/byte
  SHA-512                  :        614 Kb/s,        191 cycles/byte
  AES-CBC-128              :       1355 Kb/s,         86 cycles/byte
  AES-CBC-192              :       1191 Kb/s,         98 cycles/byte
  AES-CBC-256              :       1063 Kb/s,        110 cycles/byte
  AES-GCM-128              :        440 Kb/s,        267 cycles/byte
  AES-GCM-192              :        421 Kb/s,        279 cycles/byte
  AES-GCM-256              :        404 Kb/s,        291 cycles/byte
  AES-CCM-128              :        587 Kb/s,        200 cycles/byte
  AES-CCM-192              :        524 Kb/s,        224 cycles/byte
  AES-CCM-256              :        473 Kb/s,        248 cycles/byte
  CTR_DRBG (NOPR)          :       1110 Kb/s,        105 cycles/byte
  CTR_DRBG (PR)            :        798 Kb/s,        147 cycles/byte
  HMAC_DRBG SHA-256 (NOPR) :        234 Kb/s,        504 cycles/byte
  HMAC_DRBG SHA-256 (PR)   :        205 Kb/s,        574 cycles/byte
  RSA-2048                 :      30 ms/ public
  RSA-2048                 :    1037 ms/private
  RSA-4096                 :     100 ms/ public
  RSA-4096                 :    5738 ms/private
  ECDSA-secp384r1          :

Environment:
Ubuntu 14.04 virtual machine
mbed-cli v.0.9.7
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529

**Comment by andresag01** [comment]
PR fixes this issue https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/11
