### ISSUE TITLE
Meet problem when run "mbed compile -m K64F -t GCC_ARM"

### ISSUE THREAD

**Issue by Andi2016** [ARMmbed/oob-mbed-os-example-tls#23]
We met problem when we run `mbed compile -m K64F -t GCC_ARM` in our mac terminal.
<img width="1218" alt="screen shot 2016-10-19 at 10 23 54" src="https://cloud.githubusercontent.com/assets/17850652/19503452/36d8c440-95e6-11e6-88ef-d924fd1bd4de.png">

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1055

**Comment by c1728p9** [comment]
Hi @Andi2016, this looks like a tool error. Do you have ```GNU Tools ARM Embedded``` installed and added to path?

**Comment by Andi2016** [comment]
Yeah, that works, thx
