### ISSUE TITLE
mbed export to IAR: debug error

### ISSUE THREAD

**Issue by MaggieMei** [ARMmbed/oob-mbed-os-example-tls#24]
command:

```
mbed export -m K64F -i iar
```

compile can be finished successfully but can't enter into the debug mode

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1054

**Comment by 0xc0170** [comment]
Fixed on master, should be part of RC4, please retest for OOB round 4.

**Comment by sbutcher-arm** [comment]
Closing as not an issue with mbed TLS or the example code (and should be fixed anyway).
