### ISSUE TITLE
Hashing Online IDE compile error 

### ISSUE THREAD

**Issue by MaggieMei** [ARMmbed/oob-mbed-os-example-tls#26]
```
Error: Expected an expression in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 65, Col: 11
Error: Identifier "s" is undefined in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 65, Col: 30
Error: Expected an expression in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 104, Col: 11
Error: Identifier "es" is undefined in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 104, Col: 47
Error: Expected an expression in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 105, Col: 15
Error: Identifier "e" is undefined in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 105, Col: 50
Error: Expected an expression in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 134, Col: 11
Error: Identifier "p" is undefined in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 134, Col: 50
Error: Expected an expression in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 333, Col: 15
Error: Identifier "e" is undefined in "extras/tls-client/mbed-os.lib/events/equeue/equeue.c", Line: 333, Col: 44
```

**Comment by ashok-rao** [comment]
@MaggieMei , you have to delete the other examples folders from the project in the online IDE. I faced this issue too. It compiles fine after deleting the other examples & just leave the hashing (or whichever you are testing) in there. Can you please check this?

cc @screamerbg ..

**Comment by MarceloSalazar** [comment]
Same problem as this one: https://github.com/ARMmbed/oob-mbed-os-example-ble/issues/21

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1052

**Comment by MarceloSalazar** [comment]
Discussed internally. There is no easy fix for this release.
The workaround is to delete other folders as commented in https://github.com/ARMmbed/oob-mbed-os-example-tls/issues/26#issuecomment-254755562

The solution is to split the examples into multiple github repos.
Conversations to start after the 5.2 release @sbutcher-arm

**Comment by sg-** [comment]
The examples come from developer.mbed.org/teams/mbed-os-example team repos for a release. This should be resolved when the release is made.
