### ISSUE TITLE
Benchmark example ARM build halts

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-tls#3]
Build and flashed benchmark example to K64F with ARM. 
Application does not print anything.

Environment:
Ubuntu 14.04 virtual machine
mbed-cli v.0.9.7
ARM Compiler 5.06 update 4 (build 422)

**Comment by andresag01** [comment]
PR fixes this issue https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/11
