### ISSUE TITLE
tls-client ARM build handshake fails

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-tls#6]
ARM build could not connect with developer.mbed.com

Using Ethernet LWIP
Client IP Address is 192.168.100.16
Connecting with developer.mbed.org
Starting the TLS handshake...
mbedtls_ssl_handshake() failed: -0x262e (-9774): X509 - Signature algorithm (oid) is unsupported : OID - OID is not found
MBED: Socket Error: -1

Environment:
Ubuntu 14.04 virtual machine
mbed-cli v.0.9.7
ARM Compiler 5.06 update 4 (build 422)

**Comment by terhei** [comment]
Same issue with nucleo_f429zi

**Comment by andresag01** [comment]
PR https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/10 fixes this issue and has already been merged.
